version: '2'

services:
  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on: 
      - rabbitmq
    command: rabbitmq:5672
  
  fibonacci-api:
    image: fibonacci-api
    links:
      - rabbitmq
    ports:
      - '5000:5000'

  fibonacci-service:
    image: fibonacci-service
    links:
      - rabbitmq
    ports:
      - '5050:5050'

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - '5672:5672'